chore: Add more error logging to processor (#396)
Currently, when a file cannot be found, the proof processor provides the
following error:
```
Error: No such file or directory (os error 2)
```
Which does not provide any information about where the error occurred.

With these changes, the error becomes:
```
Error: Error while creating proof reader for scaffold

Caused by:
    No such file or directory (os error 2)
```

I am more than open to suggestions of how to handle this properly.

---------

Co-authored-by: Maarten Flippo <maartenflippo@outlook.com>